/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/

export const MODAL = {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
};

export const STAFFS = {
    GET_LIST_STAFFS: "GET_LIST_STAFFS",
    LOADING_STAFFS: "LOADING_STAFFS",
    ADD_STAFFS: "ADD_STAFFS",
    UPDATE_STAFFS: "UPDATE_STAFFS",
    DELETE_STAFFS: "DELETE_STAFFS",
};

export const PRODUCTS = {
    GET_LIST_PRODUCTS: "GET_LIST_PRODUCTS",
    LOADING_PRODUCTS: "LOADING_PRODUCTS",
    ADD_PRODUCTS: "ADD_PRODUCTS",
    UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
    DELETE_PRODUCTS: "DELETE_PRODUCTS",
};

export const SALARY = {
    GET_LIST_SALARY: "GET_LIST_SALARY",
    LOADING_SALARY: "LOADING_SALARY",
    ADD_SALARY: "ADD_SALARY",
    UPDATE_SALARY: "UPDATE_SALARY",
    DELETE_SALARY: "DELETE_SALARY",
};

export const STORE_OUTSIDE = {
    GET_LIST_STORE_OUTSIDE: "GET_LIST_STORE_OUTSIDE",
    LOADING_STORE_OUTSIDE: "LOADING_STORE_OUTSIDE",
    ADD_STORE_OUTSIDE: "ADD_STORE_OUTSIDE",
    UPDATE_STORE_OUTSIDE: "UPDATE_STORE_OUTSIDE",
    DELETE_STORE_OUTSIDE: "DELETE_STORE_OUTSIDE",
};

export const CUSTOMER = {
    GET_LIST_CUSTOMER: "GET_LIST_CUSTOMER",
    LOADING_CUSTOMER: "LOADING_CUSTOMER",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
};
