/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/

export const MODAL = {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
};

export const STAFFS = {
    GET_LIST_STAFFS: "GET_LIST_STAFFS",
    LOADING_STAFFS: "LOADING_STAFFS",
    ADD_STAFFS: "ADD_STAFFS",
    UPDATE_STAFFS: "UPDATE_STAFFS",
    DELETE_STAFFS: "DELETE_STAFFS",
};

export const PRODUCTS = {
    GET_LIST_PRODUCTS: "GET_LIST_PRODUCTS",
    LOADING_PRODUCTS: "LOADING_PRODUCTS",
    ADD_PRODUCTS: "ADD_PRODUCTS",
    UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
    DELETE_PRODUCTS: "DELETE_PRODUCTS",
};
